### ISSUE TITLE
Sigularity approach : Authentication failed, retrying ...

### ISSUE THREAD

**Issue by HandmannP** [geomar-od/example-cmems-download-automation#31]
I am currently trying to get the singularity approach to work on the nesh and get this authentication error:
2021-11-23 10:11:12.719 [WARNING] Warning: Authentication failed, retrying in 300 seconds …
 I am trying to download daily GLOBAL_REANALYSIS_PHY_001_030-TDS data for the area of     --longitude_min 0 --longitude_max 150 \
    --latitude_min -80 --latitude_max 30 \ . 
Find the Code below:

singularity run -B $PWD:/_Work \
    rasmus-cmems-downloads_motupydownload-latest.sif \
    --service_id GLOBAL_REANALYSIS_PHY_001_030-TDS \
    --product_id global-reanalysis-phy-001-030-daily \
    --time_min 1993-01-01 --time_max 2019-12-31 \
    --var bottomT --var mlotst --var siconc \
    --var sithick --var so --var thetao \
    --var uo --var usi --var vo \
    --var vsi --var zos \
    --basedir /_Work/GLOBAL_REANALYSIS_PHY_001_030-TDS

Does anybody experience the same problem?

**Comment by willirath** [comment]
What's the error if you deliberately use wrong credentials?

**Comment by eshchekinova** [comment]
In your call try to explicitly insert "--motu"  as follows:

singularity run -B $PWD:/_Work
rasmus-cmems-downloads_motupydownload-latest.sif
--motu https://my.cmems-du.eu/motu-web/Motu
--service_id GLOBAL_REANALYSIS_PHY_001_030-TDS
--product_id global-reanalysis-phy-001-030-daily
--time_min 1993-01-01 --time_max 2019-12-31
--var bottomT --var mlotst --var siconc
--var sithick --var so --var thetao
--var uo --var usi --var vo
--var vsi --var zos
--basedir /_Work/GLOBAL_REANALYSIS_PHY_001_030-TDS

The Python script for downloading the corresponding product can be retrieved at https://resources.marine.copernicus.eu/product-download/GLOBAL_REANALYSIS_PHY_001_030.

**Comment by willirath** [comment]
Also, I'm not sure if inside the singularity container, the exported vars from the host system are available. These might need to be passed inside.

**Comment by HandmannP** [comment]
> What's the error if you deliberately use wrong credentials?

Why should I use wrong credentials? I am using the login data that works to connect my computer with the ftp - it works fine.

**Comment by HandmannP** [comment]
> In your call try to explicitly insert "--motu" as follows:
> 
> singularity run -B $PWD:/_Work rasmus-cmems-downloads_motupydownload-latest.sif 
--motu https://my.cmems-du.eu/motu-web/Motu 
--service_id GLOBAL_REANALYSIS_PHY_001_030-TDS 
--product_id global-reanalysis-phy-001-030-daily
--time_min 1993-01-01 --time_max 2019-12-31 
--var bottomT --var mlotst --var siconc --var sithick --var so --var thetao --var uo --var usi --var vo --var vsi --var zos 
--basedir /_Work/GLOBAL_REANALYSIS_PHY_001_030-TDS
> 
> The Python script for downloading the corresponding product can be retrieved at https://resources.marine.copernicus.eu/product-download/GLOBAL_REANALYSIS_PHY_001_030.

Hey, so I tried this now and get a new error:

usage: motupydownload.py [-h] [--basedir BASEDIR] [--longitude_min LONGITUDE_MIN]
                         [--longitude_max LONGITUDE_MAX] [--latitude_min LATITUDE_MIN]
                         [--latitude_max LATITUDE_MAX] [--depth_min DEPTH_MIN] [--depth_max DEPTH_MAX]
                         [--time_min TIME_MIN] [--time_max TIME_MAX] [--var VAR] [--service_id SERVICE_ID]
                         [--product_id PRODUCT_ID] [--server_address SERVER_ADDRESS]
                         [--parallel_downloads PARALLEL_DOWNLOADS] [--replace]
motupydownload.py: error: unrecognized arguments: --motu https://my.cmems-du.eu/motu-web/Motu

And there was indeed a problem with my password - utf8 characters have to be handled with caution - ! should be inserted as "'!'"...

The other point that I do not understand is the way to apply the python code here?

Thanks for your patience.

**Comment by HandmannP** [comment]
short update : I am trying it through a Jupiter nb now - I get a CAS error now. the script is attached - there is motuclient and 
maskpass installed.
The Error is now : 
Warning: CAS connection failed, retrying in 10 seconds ...
Warning: CAS connection failed, retrying in 30 seconds ...
Warning: CAS connection failed, retrying in 100 seconds ...

and finally : 
URLError: <urlopen error [Errno -2] Name or service not known>

[motuclient_within_jupyter_nb.txt](https://github.com/geomar-od/rasmus-cmems-downloads/files/7595180/motuclient_within_jupyter_nb.txt)

[files-recursive.txt](https://github.com/geomar-od/rasmus-cmems-downloads/files/7595187/files-recursive.txt)

**Comment by eshchekinova** [comment]
For me the following sequence worked well for the data set you required. 
Before, please remove old .sif files from the same directory. 
So , instead of "--motu", "--server_address" must be used.  

singularity run -B $PWD:/_Work \
      rasmus-cmems-downloads_motupydownload-latest.sif \
      --server_address https://my.cmems-du.eu/motu-web/Motu \
      --service_id GLOBAL_REANALYSIS_PHY_001_030-TDS \
      --product_id global-reanalysis-phy-001-030-daily \
      --time_min 1993-01-01 --time_max 2019-12-31 \
      --var bottomT --var mlotst --var siconc \
      --var sithick --var so --var thetao \
      --var uo --var usi --var vo \
      --var vsi --var zos \
      --basedir /_Work/GLOBAL_REANALYSIS_PHY_001_030-TDS \

**Comment by eshchekinova** [comment]
With end of line signs (\):
singularity run -B $PWD:/_Work \
         rasmus-cmems-downloads_motupydownload-latest.sif \
         --server_address https://my.cmems-du.eu/motu-web/Motu \
         --service_id GLOBAL_REANALYSIS_PHY_001_030-TDS \
         --product_id global-reanalysis-phy-001-030-daily \
         --time_min 1993-01-01 --time_max 2019-12-31 \
         --var bottomT --var mlotst --var siconc \
         --var sithick --var so --var thetao \
         --var uo --var usi --var vo \
         --var vsi --var zos \
         --basedir /_Work/GLOBAL_REANALYSIS_PHY_001_030-TDS \

**Comment by HandmannP** [comment]
Thank you ! Now it works fine

**Comment by willirath** [comment]
> Why should I use wrong credentials? I am using the login data that works to connect my computer with the ftp - it works fine.

For checking if the error is about wrong credentials or if there's another problem with the authentication.
